export const PERMISSIONS = {
  // User management
  CREATE_USER: 'create_user',
  VIEW_USERS: 'view_users',
  UPDATE_USER: 'update_user',
  DELETE_USER: 'delete_user',
  ACTIVATE_USER: 'activate_user',
  SUSPEND_USER: 'suspend_user',

  // Intern management
  VIEW_INTERNS: 'view_interns',
  CREATE_INTERN: 'create_intern',
  UPDATE_INTERN: 'update_intern',
  DELETE_INTERN: 'delete_intern',
  EVALUATE_INTERN: 'evaluate_intern',
  VIEW_INTERN_READINESS: 'view_intern_readiness',

  // Company management
  VIEW_COMPANIES: 'view_companies',
  CREATE_COMPANY: 'create_company',
  UPDATE_COMPANY: 'update_company',
  DELETE_COMPANY: 'delete_company',
  VERIFY_COMPANY: 'verify_company',

  // Assessment management
  VIEW_ASSESSMENTS: 'view_assessments',
  CREATE_ASSESSMENT: 'create_assessment',
  UPDATE_ASSESSMENT: 'update_assessment',
  DELETE_ASSESSMENT: 'delete_assessment',
  TAKE_ASSESSMENT: 'take_assessment',
  EVALUATE_ASSESSMENT: 'evaluate_assessment',

  // Training management
  VIEW_TRAININGS: 'view_trainings',
  CREATE_TRAINING: 'create_training',
  UPDATE_TRAINING: 'update_training',
  DELETE_TRAINING: 'delete_training',
  ENROLL_TRAINING: 'enroll_training',
  MANAGE_TRAINING_PROGRESS: 'manage_training_progress',

  // Project management
  VIEW_PROJECTS: 'view_projects',
  CREATE_PROJECT: 'create_project',
  UPDATE_PROJECT: 'update_project',
  DELETE_PROJECT: 'delete_project',
  ASSIGN_PROJECT: 'assign_project',
  SUBMIT_PROJECT_WORK: 'submit_project_work',
  REVIEW_PROJECT_WORK: 'review_project_work',

  // Matching & Hiring
  VIEW_OPPORTUNITIES: 'view_opportunities',
  CREATE_OPPORTUNITY: 'create_opportunity',
  APPLY_OPPORTUNITY: 'apply_opportunity',
  VIEW_APPLICATIONS: 'view_applications',
  REVIEW_APPLICATION: 'review_application',
  SCHEDULE_INTERVIEW: 'schedule_interview',
  MAKE_OFFER: 'make_offer',

  // Analytics & Reports
  VIEW_ANALYTICS: 'view_analytics',
  VIEW_REPORTS: 'view_reports',
  GENERATE_REPORT: 'generate_report',
  EXPORT_DATA: 'export_data',

  // System management
  VIEW_SYSTEM_SETTINGS: 'view_system_settings',
  UPDATE_SYSTEM_SETTINGS: 'update_system_settings',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  MANAGE_BACKUP: 'manage_backup',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ADMIN_PERMISSIONS = Object.values(PERMISSIONS);
export const HR_PERMISSIONS = [
  PERMISSIONS.VIEW_USERS,
  PERMISSIONS.CREATE_USER,
  PERMISSIONS.UPDATE_USER,
  PERMISSIONS.ACTIVATE_USER,
  PERMISSIONS.SUSPEND_USER,
  PERMISSIONS.VIEW_INTERNS,
  PERMISSIONS.CREATE_INTERN,
  PERMISSIONS.UPDATE_INTERN,
  PERMISSIONS.VIEW_COMPANIES,
  PERMISSIONS.CREATE_COMPANY,
  PERMISSIONS.UPDATE_COMPANY,
  PERMISSIONS.VERIFY_COMPANY,
  PERMISSIONS.VIEW_ASSESSMENTS,
  PERMISSIONS.EVALUATE_ASSESSMENT,
  PERMISSIONS.VIEW_TRAININGS,
  PERMISSIONS.VIEW_PROJECTS,
  PERMISSIONS.VIEW_OPPORTUNITIES,
  PERMISSIONS.VIEW_ANALYTICS,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.GENERATE_REPORT,
];

export const MANAGER_PERMISSIONS = [
  PERMISSIONS.VIEW_USERS,
  PERMISSIONS.VIEW_INTERNS,
  PERMISSIONS.UPDATE_INTERN,
  PERMISSIONS.EVALUATE_INTERN,
  PERMISSIONS.VIEW_PROJECTS,
  PERMISSIONS.CREATE_PROJECT,
  PERMISSIONS.UPDATE_PROJECT,
  PERMISSIONS.ASSIGN_PROJECT,
  PERMISSIONS.REVIEW_PROJECT_WORK,
  PERMISSIONS.VIEW_TRAININGS,
  PERMISSIONS.ENROLL_TRAINING,
  PERMISSIONS.MANAGE_TRAINING_PROGRESS,
  PERMISSIONS.VIEW_REPORTS,
];

export const INTERN_PERMISSIONS = [
  PERMISSIONS.VIEW_USERS,
  PERMISSIONS.VIEW_INTERNS,
  PERMISSIONS.VIEW_ASSESSMENTS,
  PERMISSIONS.TAKE_ASSESSMENT,
  PERMISSIONS.VIEW_TRAININGS,
  PERMISSIONS.ENROLL_TRAINING,
  PERMISSIONS.MANAGE_TRAINING_PROGRESS,
  PERMISSIONS.VIEW_PROJECTS,
  PERMISSIONS.SUBMIT_PROJECT_WORK,
  PERMISSIONS.VIEW_OPPORTUNITIES,
  PERMISSIONS.APPLY_OPPORTUNITY,
];

export const COMPANY_PERMISSIONS = [
  PERMISSIONS.VIEW_USERS,
  PERMISSIONS.VIEW_COMPANIES,
  PERMISSIONS.UPDATE_COMPANY,
  PERMISSIONS.VIEW_OPPORTUNITIES,
  PERMISSIONS.CREATE_OPPORTUNITY,
  PERMISSIONS.VIEW_APPLICATIONS,
  PERMISSIONS.REVIEW_APPLICATION,
  PERMISSIONS.SCHEDULE_INTERVIEW,
  PERMISSIONS.MAKE_OFFER,
  PERMISSIONS.VIEW_ANALYTICS,
  PERMISSIONS.VIEW_REPORTS,
];