export const ROLES = {
  ADMIN: 'admin',
  HR: 'hr',
  MANAGER: 'manager',
  INTERN: 'intern',
  COMPANY: 'company',
  MENTOR: 'mentor',
  EVALUATOR: 'evaluator',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  admin: ['*'],
  hr: [
    'view_interns',
    'manage_interns',
    'view_companies',
    'manage_companies',
    'view_assessments',
    'manage_assessments',
    'view_trainings',
    'manage_trainings',
    'view_reports',
    'manage_reports',
    'manage_users',
    'view_analytics',
  ],
  manager: [
    'view_interns',
    'manage_team_interns',
    'view_projects',
    'manage_projects',
    'view_assessments',
    'evaluate_interns',
    'view_trainings',
    'manage_team_training',
    'view_reports',
    'view_team_reports',
    'approve_leave',
  ],
  intern: [
    'view_profile',
    'update_profile',
    'view_assessments',
    'take_assessments',
    'view_trainings',
    'enroll_training',
    'view_projects',
    'submit_project',
    'view_opportunities',
    'apply_opportunities',
    'view_attendance',
    'manage_attendance',
    'view_communications',
    'send_messages',
  ],
  company: [
    'view_company_profile',
    'update_company_profile',
    'post_requirements',
    'view_applications',
    'review_applications',
    'view_matches',
    'schedule_interviews',
    'view_hire_interns',
    'view_analytics',
  ],
  mentor: [
    'view_projects',
    'manage_projects',
    'view_interns',
    'evaluate_interns',
    'view_trainings',
    'conduct_training',
    'view_communications',
    'send_messages',
  ],
  evaluator: [
    'view_assessments',
    'evaluate_assessments',
    'view_interns',
    'view_results',
    'provide_feedback',
  ],
};

export const ROLE_HIERARCHY = {
  admin: 0,
  hr: 1,
  manager: 2,
  mentor: 3,
  evaluator: 4,
  company: 5,
  intern: 6,
} as const;

export const DEFAULT_ROUTES = {
  admin: '/admin/dashboard',
  hr: '/hr/dashboard',
  manager: '/manager/dashboard',
  intern: '/dashboard',
  company: '/company/dashboard',
  mentor: '/mentor/dashboard',
  evaluator: '/evaluator/dashboard',
} as const;